### ISSUE TITLE
Doesn't work on 5.26

### ISSUE THREAD

**Issue by Four-Ninez** [Ecco-SC/Ecco#9]
Logs from logfile::

ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (46, 153) : Expected one of: ,, )
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (58, 6) : Expected expression value
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (58, 6) : Instead found ')'
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (59, 164) : Expected one of: ,, )
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (70, 6) : Expected expression value
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (70, 6) : Instead found ')'
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (71, 152) : Expected one of: ,, )
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (79, 6) : Expected expression value
ERROR: c:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/Ecco/Ecco.as (79, 6) : Instead found ')'
ERROR: Plugin script compilation failed

Looks like a syntax error so fixing it shouldn't be a problem

**Comment by darkfvtvre** [comment]
Seems like NPC spawning is still nonworking.  Everything else works though.
